### ISSUE TITLE
Sometimes works sometimes not???

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Discord-Webhook-Protector#10]
![image](https://user-images.githubusercontent.com/86944806/170248890-6d009c25-04bc-449d-abe3-908d445bd596.png)
I used hazard v2 with the webhook protector and ran the .py file 2 times with interval of few seconds.
The first time it sent and the second time it didnt... My ratelimit is set to 100ms so idk why it did this and also this not first time.
Many times it just gives error code 401 in the log when the grabber is run idk why eventhough password is correct it many times not work. 

Is there a way to remove the ratelimit function from the webhook protector?

**Comment by Rdimo** [comment]
@PandoricGalaxy try and see now, it might be fixed

**Comment by PandoricGalaxy** [comment]
> @PandoricGalaxy try and see now, it might be fixed

Alr8 it'll take 10 mins

**Comment by PandoricGalaxy** [comment]
Its better now but still wish to be able to toggle rate limiting on or off
![image](https://user-images.githubusercontent.com/86944806/170420745-fc57ce19-49be-4154-be37-5b4f34f6cb3f.png)

**Comment by PandoricGalaxy** [comment]
@Rdimo ?

**Comment by PandoricGalaxy** [comment]
Just last request that u add toggle for ratelimit since it breaks the requests and causes sometimes to not send the file and ratelimit even if it's real so just a way to turn it off is all needed!!

**Comment by Rdimo** [comment]
added all of this some hours ago now
