### ISSUE TITLE
Yet again.....

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Discord-Webhook-Protector#11]
![image](https://user-images.githubusercontent.com/86944806/171480395-aab1c867-9da6-42bc-aabf-f9bb77f9d8ef.png)
this happens... so to test it some times and yyes its like this... 

I have checked and the password is indeed right but still sometimes it doesnt send and shows this and sometimes it sends either file or embed

**Comment by Rdimo** [comment]
> ![image](https://user-images.githubusercontent.com/86944806/171480395-aab1c867-9da6-42bc-aabf-f9bb77f9d8ef.png) this happens... so to test it some times and yyes its like this...
> 
> I have checked and the password is indeed right but still sometimes it doesn't send and shows this and sometimes it sends either file or embed

so the key is correct and it only sends it sometimes?

**Comment by Rdimo** [comment]
you didnt add any options by any chance to the totp calls right?

**Comment by PandoricGalaxy** [comment]
> > ![image](https://user-images.githubusercontent.com/86944806/171480395-aab1c867-9da6-42bc-aabf-f9bb77f9d8ef.png) this happens... so to test it some times and yyes its like this...
> > I have checked and the password is indeed right but still sometimes it doesn't send and shows this and sometimes it sends either file or embed
> 
> so the key is correct and it only sends it sometimes?

Yeah the key is correct

**Comment by PandoricGalaxy** [comment]
> you didnt add any options by any chance to the totp calls right?

Nope didn't change a thing try yourself by opening it a few times with a little interval u might also get it

**Comment by Rdimo** [comment]
> > you didnt add any options by any chance to the totp calls right?
> 
> Nope didn't change a thing try yourself by opening it a few times with a little interval u might also get it

right lemme see

**Comment by Rdimo** [comment]
it works fine for me

**Comment by PandoricGalaxy** [comment]
> it works fine for me

Strange... Did u try opening many instances of test and check ?

**Comment by Rdimo** [comment]
> > it works fine for me
> 
> Strange... Did u try opening many instances of test and check ?

yup

**Comment by Rdimo** [comment]
think it might be the totp code then, ill have a look on it

**Comment by Rdimo** [comment]
make sure this isnt a "you only" thing too since I havent heard of anyone else getting the issues that ur getting

**Comment by PandoricGalaxy** [comment]
Oh lol forgot to close this sorry it's a "me only" thing... Also since hazard won't be made op anymore should I implement little features like self destruct and, download and run exe in it? I'll create pull request if u are ready
