### ISSUE TITLE
can someone help me

### ISSUE THREAD

**Issue by jack11e** [Rdimo/Discord-Webhook-Protector#13]
![Screenshot 2022-06-04 153513](https://user-images.githubusercontent.com/90142021/172023076-04a8783b-eea8-4be7-adb2-46a85c6e03cf.png)

I did pip install pyperclip and installed teh rest of the requierments

**Comment by jack11e** [comment]
i did pip install pyperclip

**Comment by dekrypted** [comment]
That's just for testing. You're not supposed to use the .py files.

**Comment by Rdimo** [comment]
> That's just for testing. You're not supposed to use the .py files.

no ur supposed to use them if you want it to go quicker, its not mandatory ofc but for the keygen.py atleast you need it
