### ISSUE TITLE
error code i need help

### ISSUE THREAD

**Issue by Mago126** [Rdimo/Discord-Webhook-Protector#15]
after typing "git push heroku main"
error: src refspec main does not match any
error: failed to push some refs to 'https://git.heroku.com/floating-plateau-22375.git' ???? what should i do

**Comment by Mago126** [comment]
![image](https://user-images.githubusercontent.com/106020383/173177231-cb759ecc-bb8d-4bf3-8d5c-0092c8e5915f.png)

**Comment by Rdimo** [comment]
read the readme
