### ISSUE TITLE
Use in other languages

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Discord-Webhook-Protector#16]
I wanted to know how can it be used in other languages. I mainly want to know how to use it in batchfile since I don't think I can import pyotp in it.

**Comment by Rdimo** [comment]
> I wanted to know how can it be used in other languages. I mainly want to know how to use it in batchfile since I don't think I can import pyotp in it.

yes this can be used in any language, one issue is the totp since some languages don't have a package for that which leads to you having to make your own

**Comment by PandoricGalaxy** [comment]
How can I do it for batchfile ?

**Comment by PandoricGalaxy** [comment]
How do I use it for node.js ?
