### ISSUE TITLE
file upload support

### ISSUE THREAD

**Issue by xrevix** [Rdimo/Discord-Webhook-Protector#2]
can i upload file to it ?

**Comment by Rdimo** [comment]
> can i upload file to it ?
no not yet. I think ill update this later tho to make it be able to accept files so you can just make a post request to this api exactly like you can with a normal discord webhook

**Comment by Rdimo** [comment]
![image](https://user-images.githubusercontent.com/80375661/168429768-3ee9119e-259d-404c-850a-51777f353c33.png)
stated it here too

**Comment by xrevix** [comment]
ok Thx👀

**Comment by freegocrazy** [comment]
hse working on it right now btw

**Comment by Rdimo** [comment]
I pretty much just got done with it, adding a bunch of stuff to it like ratelimit, config/settings, better logs, made it in typescript now too and ofc file upload support

**Comment by Rdimo** [comment]
alr added this now @xrevix
