### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Discord-Webhook-Protector#5]
at=error code=H10 desc="App crashed" method=POST path="/" <- Heroku log

happens when i run test.py . correct api and password used

**Comment by Rdimo** [comment]
> at=error code=H10 desc="App crashed" method=POST path="/" <- Heroku log
> 
> happens when i run test.py . correct api and password used

yes this is now fixed

**Comment by PandoricGalaxy** [comment]
> > at=error code=H10 desc="App crashed" method=POST path="/" <- Heroku log
> > happens when i run test.py . correct api and password used
> 
> yes this is now fixed

Thanks!!!

**Comment by Rdimo** [comment]
> > > at=error code=H10 desc="App crashed" method=POST path="/" <- Heroku log
> > > happens when i run test.py . correct api and password used
> > 
> > 
> > yes this is now fixed
> 
> Thanks!!!

np 😘
