### ISSUE TITLE
;

### ISSUE THREAD

**Issue by xrevix** [Rdimo/Discord-Webhook-Protector#6]
its Working Well nice !
is there any other free host to use ?
 i dont want to use heroku.

**Comment by Rdimo** [comment]
> 

lmao ye ik heroku isnt the best but I choose it for the simplicity and easy setup, you could use a vps with this and it will work just as well but im not sure about any other hosting sites

**Comment by PandoricGalaxy** [comment]
> its Working Well nice ! is there any other free host to use ? i dont want to use heroku.

Yes there is a better one read [this](https://github.com/Rdimo/Discord-Webhook-Protector#render)
