### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Discord-Webhook-Protector#7]
_**solved**_

**Comment by Rdimo** [comment]
right that means that ur key is not a base32 encoding so just make one

**Comment by PandoricGalaxy** [comment]
> right that means that ur key is not a base32 encoding so just make one

alr8 i did it and now it says ok401
![image](https://user-images.githubusercontent.com/86944806/169709105-ee7dde08-f62f-4c9e-be1f-9ed08f8c3af4.png)

**Comment by Rdimo** [comment]
> > right that means that ur key is not a base32 encoding so just make one
> 
> alr8 i did it and now it says ok401 ![image](https://user-images.githubusercontent.com/86944806/169709105-ee7dde08-f62f-4c9e-be1f-9ed08f8c3af4.png) but nothing sent to webhook

yes the key in your api needs to be the same in the test one too

**Comment by PandoricGalaxy** [comment]
> > > right that means that ur key is not a base32 encoding so just make one
> > 
> > 
> > alr8 i did it and now it says ok401 ![image](https://user-images.githubusercontent.com/86944806/169709105-ee7dde08-f62f-4c9e-be1f-9ed08f8c3af4.png) but nothing sent to webhook
> 
> yes the key in your api needs to be the same in the test one too

it is

**Comment by PandoricGalaxy** [comment]
![image](https://user-images.githubusercontent.com/86944806/169709391-5b61d116-bb77-4e66-a062-d744f48c9443.png)
![image](https://user-images.githubusercontent.com/86944806/169709406-d53e16b8-5ca1-4989-a73c-b8c510ad24a6.png)

**Comment by PandoricGalaxy** [comment]
Ahh it worked now nvm just changed the ' to " in test.py

**Comment by Rdimo** [comment]
> Ahh it worked now nvm just changed the ' to " in test.py

lmao alr

**Comment by Rdimo** [comment]
wait what that shoudln't have been the solution, think the problem was that you first made an invalid request which made you get ratelimited and then when you had the key correct you were still reatelimited
