### ISSUE TITLE
Switch from Heroku to Render

### ISSUE THREAD

**Issue by PandoricGalaxy** [Rdimo/Discord-Webhook-Protector#8]
The title itslef...
How do i run this on [render](https://render.com) since it offers 750 free monthly hours i believe

**Comment by Rdimo** [comment]
still wanan keep heroku tho just for more options

**Comment by PandoricGalaxy** [comment]
Yeahh I'll just copy paste and update the readme with even render tutorial and I'll let u decide if u wanna put it

**Comment by PandoricGalaxy** [comment]
> > Yeahh I'll just copy paste and update the readme with even render tutorial and I'll let u decide if u wanna put it
> 
> yaya yaya

https://github.com/Rdimo/Discord-Webhook-Protector/pull/9

Done just take a look and accept it

**Comment by PandoricGalaxy** [comment]
@Rdimo ?
